import pandas as pd
data = pd.read_csv("data.csv",index_col="Name") # this will read the data from the file "data.csv" and create a DataFrame object called "data". The read_csv function is used to read a comma-separated values (CSV) file into a DataFrame. The resulting DataFrame will have columns corresponding to the headers in the CSV file and rows corresponding to the data entries in the file.
#selecting columns
print(data["Name","Height"]) # this will print the columns "Name" and "Height" from the DataFrame "data". The column selection data["Name","Height"] is used to select specific columns from the DataFrame. In this case, we are selecting the columns "Name" and "Height", which will return a new DataFrame containing only those two columns.
#selecting rows
# print(data.loc["pikachu"]) # this will print the row at index 0 
#selecting rows and columns
# print(data.loc[0:2,"Name":"Height"]) # this will print the rows from index 0 to index 2 and the columns from "Name" to "Height" from the DataFrame "data". The loc function is used to access a group of rows and columns by labels or a boolean array. In this case, we are using it to access a range of rows from index 0 to index 2 and a range of columns from "Name" to "Height". The resulting DataFrame will contain the specified rows and columns based on the provided labels.
# print(data.iloc[0:2,0:2]) # this will print the rows from index 0 to index 2 and the columns from index 0 to index 2 from the DataFrame "data". The iloc function is used to access a group of rows and columns by integer position. In this case, we are using it to access a range of rows from index 0 to index 2 and a range of columns from index 0 to index 2. The resulting DataFrame will contain the specified rows and columns based on their integer positions in the DataFrame.
# print(data[data["Height"]>0.5]) # this will print the rows from the DataFrame "data" where the value in the "Height" column is greater than 0.5. The condition data["Height"]>0.5 creates a boolean series that indicates which rows in the DataFrame satisfy the condition, and then we use this boolean series to filter the original DataFrame and return only the rows that satisfy the condition.