s=set()
n=input("enter the  element of the set:")
s.add(int(n))
n=input("enter the  element of the set:")
s.add(int(n))
n=input("enter the  element of the set:")
s.add(int(n))
n=input("enter the  element of the set:")
s.add(int(n))       
n=input("enter the  element of the set:")
s.add(int(n))
n=input("enter the  element of the set:")
s.add(int(n))
n=input("enter the  element of the set:")
s.add(int(n))
n=input("enter the  element of the set:")
s.add(int(n))
n=input("enter the  element of the set:")
s.add(int(n))
print(s)